version: '3'
services:
  wallet-app:
    build:
      context: .
    container_name: wallet-app
    volumes:
      - ./:/var/www
    depends_on:
      - wallet-mysql
      - wallet-redis
    networks:
      - app-network
    dns:
      - 8.8.8.8

  wallet-mysql:
    build: ./.docker/mysql
    command: --innodb-use-native-aio=0
    container_name: wallet-db
    restart: always
    ports:
      - "127.0.0.1:3308:3306"
    environment:
      MYSQL_DATABASE: wallet
      MYSQL_USER: wallet-user
      MYSQL_PASSWORD: Bv4erDx6YR65
      MYSQL_ROOT_PASSWORD: Bv4erDx6YR65
    networks:
      - app-network

  wallet-redis:
    image: redis:alpine
    container_name: wallet-redis
    command: redis-server --requirepass root
    ports:
      - "127.0.0.1:6380:6579"
    networks:
      - app-network

  wallet-nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./:/var/www
    depends_on:
      - wallet-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
